#!/bin/bash

file=~/Dropbox/logs/$(date +%Y.%m.%d).md

if [ -e $file ]
then
  subl $file
else
  printf "# события и эмоции\n\n\n# работа и проекты\n\n\n# чем наслаждался и за что благодарен" > $file
  subl $file
fi
