#!/usr/bin/env bash

FILE="$1"
WIDTH="$2"

if [[ -z "$FILE" || -z "$WIDTH" ]]; then
  echo "Usage: $0 <image> <width>"
  exit 1
fi

EXT="${FILE##*.}"
NAME="${FILE%.*}"

OUTPUT="${NAME}-${WIDTH}w.${EXT}"

magick "$FILE" -resize "${WIDTH}x" "$OUTPUT"

echo "Created: $OUTPUT"
