#!/usr/bin/env bash

brew upgrade yt-dlp

# слушать
mkdir -p ~/video/youtube_listen && cd ~/audio-phone
yt-dlp \
--default-search "ytsearch" \
--write-sub --sub-lang en \
--merge-output-format mp4 \
--sponsorblock-remove sponsor,selfpromo \
-S "res:1080" \
"https://www.youtube.com/playlist?list=PL7m307ZxtRxoGtg7DlMTaxnK4X9oN416J"

# отдых
mkdir -p ~/video/youtube_watch && cd ~/video/youtube_watch
yt-dlp \
-S "res:1080,fps" \
--merge-output-format mp4 \
--default-search "ytsearch" \
--write-sub --sub-lang en \
--sponsorblock-remove sponsor \
--exec "ffmpeg -i {} -c:v libx264 -preset slow -crf 18 -c:a aac -b:a 192k -movflags +faststart {}.tv.mp4 && rm {} && mv {}.tv.mp4 {}" \
"https://www.youtube.com/playlist?list=PL7m307ZxtRxob24vkJGH3u_KbsG940y7B"
